### ISSUE TITLE
Fresh Mail

### ISSUE THREAD

**Issue by michalsapka** [OneClickLab/ugly-email-trackers#14]
**Name: freh Mail**
**URL: https://freshmail.pl/**

sample pixel: http://mail.great-news.pl/o/ewhzzevkfs/zls17zdcu1/

**Comment by michalsapka** [comment]
another pixel: http://mail.mailnews.pl/o/hr16sc7i5j/dvg1262v47/

**Comment by sonnyt** [comment]
Added to the list, thank you!
