### ISSUE TITLE
Sendgrid

### ISSUE THREAD

**Issue by michalsapka** [OneClickLab/ugly-email-trackers#16]
**Name: Sendgrid**
**URL: http://sendgrid.com**

sample tracker: https://u3528416.ct.sendgrid.net/wf/open?upn=3DUFoKwCqOPvxp9ga5=
cYXKUOhUbXC9UlZeUCd28LrNXhgxh4ttwICeBH6zAmVI527QvasGn5SKZG5XlQGAgvhECNjMIzn=
qxbab3SBbk-2BUSzd51S7DN-2FnyIXBkZBtai8WLT7rjL1USYRDpGSS90RhZfh8xGAz6OnKLltt=
WZLx5jjc98yTaVYpKXr87x8XQfkPIw7VH8GUJpJi-2FvHpJhe4POe-2BVw1CwvvM2k7g-2BzzVz=
kL7E-3D

**Comment by sonnyt** [comment]
Added to the list, thank you!
