### ISSUE TITLE
Patterns from Hey.com

### ISSUE THREAD

**Issue by lifo** [OneClickLab/ugly-email-trackers#17]
Hey there,

I had been working on adding email tracker patterns to Hey.com. Here's the list of trackers that we currently have that are not present on https://trackers.uglyemail.com. Please let me know if you need any additional information.

Thanks!

**Name:** ActiveCampaign
**URL:** https://www.activecampaign.com/
**Pattern:** /lt\.php(.*)?l\=open/

**Name:** AWeber
**URL:** https://www.aweber.com/
**Pattern:** openrate.aweber.com

**Name:** Getnotify
**URL:** https://www.getnotify.com/
**Pattern:** email81.com/case

**Name:** GrowthDot
**URL:** https://www.growthdot.com/
**Pattern:** growthdot.com/api/mail-tracking

**Name:** FreshMail
**URL:** https://freshmail.com/
**Pattern:**  /\/o\/(\w){10,}\/(\w){10,}/

**Name:** Hubspot
**URL:** https://www.hubspot.com/
**Pattern:** t.hubspotemail.net

**Name:** Mailspring
**URL:** https://getmailspring.com/
**Pattern:** getmailspring.com/open

**Name:** Mandrill
**URL:** https://www.mandrill.com/
**Pattern:** mandrillapp.com/track

**Name:** Mixpanel
**URL:** https://www.mixpanel.com/
**Pattern:** api.mixpanel.com/track

**Comment by sonnyt** [comment]
Added to the list, thank you!
