### ISSUE TITLE
Superhuman

### ISSUE THREAD

**Issue by bencmbrook** [OneClickLab/ugly-email-trackers#2]
**Name:** Superhuman
**URL:** `superhuman.com` `r.superhuman.com`

Originally posted at https://github.com/OneClickLab/ugly-email-website/issues/1

They always have `r.superhuman.com` so it should be easy to add.

Example `https://r.superhuman.com/JWvaQ-CgLuLHbt4_ALpeQ32XRGQ-h1cou74ua2ZNtt8oZu=
gRza91tGfu4pygV-q-Q3CUq0qQoU0iERGHWqvbTnv2qwdp-OzuDI6kORmKkCn_bZ8WryXB-M0ap=
p7ICvyWudAH2FGFz_LuEwwy7aqgcocQ9Se8NrveNX9KmybSLC4iZ4f_.gif`

Some news about this lately
- https://twitter.com/mikeindustries/status/1146092247437340672
- https://www.nytimes.com/2019/07/09/opinion/email-tracking.html
- https://blog.superhuman.com/read-statuses-bdf0cc34b6a5 (where Superhuman recommends Ugly Email)

**Comment by sonnyt** [comment]
Added to the list, thank you!
