### ISSUE TITLE
Apple

### ISSUE THREAD

**Issue by michalsapka** [OneClickLab/ugly-email-trackers#4]
**Name Apple:**
**URL: www.apple.com**

sample pixel: https://xp.app=
le.com/report/2/its_mail_sf?responseType=3Dimage&emailType=3Dinvoice&lang=
=3Dpl_pl&eventType=3Dopen (I have in idea how this tracks, though it has width/height=1px

**Comment by sonnyt** [comment]
Added to the list, thank you!
